name: Android CI
on:
  push:
    branches: [main, master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
